### ISSUE TITLE
Multithreaded reading from DSQ

### ISSUE THREAD

**Issue by heborras** [cern-mig/python-messaging#2]
Hi,

is there a simple way to have the DSQ read by multiple threads?

So far I would go with creating a list of message names, then distributing those names to different thread, so that each will handle a portion of the total list.

Cheers,
Hendrik

**Comment by LionelCons** [comment]
Since the underlying queues support multiple concurrent readers, the easiest solution is to have one queue object per thread and let each thread work independently from the others.

**Comment by HenniOVP** [comment]
That works nicely, thank you!
